// FETCH
const FETCH_PUBLIC_MESSAGES = 'chat/FETCH_PUBLIC_MESSAGES';
const FETCH_PRIVATE_CHAT = 'chat/FETCH_PRIVATE_CHAT';

// POST
const POST_PUBLIC_MESSAGES = 'chat/POST_PUBLIC_MESSAGES';
const POST_PRIVATE_MESSAGES = 'chat/POST_PRIVATE_MESSAGES';

// SET
const SET_PUBLIC_MESSAGES = 'chat/SET_PUBLIC_MESSAGES';

// ADD
const ADD_PUBLIC_MESSAGES = 'chat/ADD_PUBLIC_MESSAGES';
const ADD_PRIVATE_CHAT = 'chat/ADD_PRIVATE_CHAT';
const ADD_PRIVATE_MESSAGES = 'chat/ADD_PRIVATE_MESSAGES';

// CLOSE
const CLOSE_CHAT = 'chat/CLOSE_CHAT';

export {
  FETCH_PUBLIC_MESSAGES,
  FETCH_PRIVATE_CHAT,
  POST_PUBLIC_MESSAGES,
  POST_PRIVATE_MESSAGES,
  SET_PUBLIC_MESSAGES,
  ADD_PUBLIC_MESSAGES,
  ADD_PRIVATE_CHAT,
  ADD_PRIVATE_MESSAGES,
  CLOSE_CHAT,
};
